import type { OnMount } from '@monaco-editor/react';

type Monaco = Parameters<OnMount>[1];

/* ---------- NASM language registration for Monaco ---------- */
let nasmRegistered = false;

export function registerNasmLanguage(monaco: Monaco) {
  if (nasmRegistered) return;
  if (
    monaco.languages.getLanguages().some((l: { id: string }) => l.id === 'nasm')
  ) {
    nasmRegistered = true;
    return;
  }
  nasmRegistered = true;

  monaco.languages.register({ id: 'nasm' });

  monaco.languages.setMonarchTokensProvider('nasm', {
    ignoreCase: true,

    keywords: [
      'mov',
      'movzx',
      'movsx',
      'movsxd',
      'movabs',
      'movdqa',
      'movdqu',
      'movaps',
      'movups',
      'lea',
      'push',
      'pop',
      'call',
      'ret',
      'retn',
      'leave',
      'enter',
      'nop',
      'int',
      'int3',
      'syscall',
      'hlt',
      'jmp',
      'je',
      'jne',
      'jz',
      'jnz',
      'ja',
      'jb',
      'jae',
      'jbe',
      'jg',
      'jl',
      'jge',
      'jle',
      'jc',
      'jnc',
      'jo',
      'jno',
      'js',
      'jns',
      'jp',
      'jnp',
      'jecxz',
      'jrcxz',
      'loop',
      'add',
      'sub',
      'mul',
      'imul',
      'div',
      'idiv',
      'inc',
      'dec',
      'neg',
      'not',
      'and',
      'or',
      'xor',
      'shl',
      'shr',
      'sar',
      'sal',
      'rol',
      'ror',
      'rcl',
      'rcr',
      'bt',
      'bts',
      'btr',
      'btc',
      'bsf',
      'bsr',
      'cmp',
      'test',
      'cmove',
      'cmovne',
      'cmovz',
      'cmovnz',
      'cmova',
      'cmovb',
      'cmovae',
      'cmovbe',
      'cmovg',
      'cmovl',
      'cmovge',
      'cmovle',
      'cmovs',
      'cmovns',
      'sete',
      'setne',
      'setz',
      'setnz',
      'seta',
      'setb',
      'setae',
      'setbe',
      'setg',
      'setl',
      'setge',
      'setle',
      'cdq',
      'cqo',
      'cbw',
      'cwde',
      'cdqe',
      'rep',
      'repe',
      'repne',
      'repz',
      'repnz',
      'movsb',
      'movsw',
      'movsd',
      'movsq',
      'stosb',
      'stosw',
      'stosd',
      'stosq',
      'lodsb',
      'lodsw',
      'lodsd',
      'lodsq',
      'scasb',
      'scasw',
      'scasd',
      'scasq',
      'cmpsb',
      'cmpsw',
      'cmpsd',
      'cmpsq',
      'xchg',
      'cmpxchg',
      'lock',
      'bswap',
      'clc',
      'stc',
      'cmc',
      'cld',
      'std',
      'in',
      'out',
      // SSE/AVX common
      'addss',
      'addsd',
      'subss',
      'subsd',
      'mulss',
      'mulsd',
      'divss',
      'divsd',
      'xorps',
      'xorpd',
      'andps',
      'andpd',
      'orps',
      'orpd',
      'comiss',
      'comisd',
      'ucomiss',
      'ucomisd',
      'cvtsi2ss',
      'cvtsi2sd',
      'cvtss2sd',
      'cvtsd2ss',
      'cvtss2si',
      'cvtsd2si',
      'pxor',
      'por',
      'pand',
      'paddb',
      'paddw',
      'paddd',
      'paddq',
    ],

    registers: [
      'rax',
      'rbx',
      'rcx',
      'rdx',
      'rsp',
      'rbp',
      'rsi',
      'rdi',
      'r8',
      'r9',
      'r10',
      'r11',
      'r12',
      'r13',
      'r14',
      'r15',
      'eax',
      'ebx',
      'ecx',
      'edx',
      'esp',
      'ebp',
      'esi',
      'edi',
      'r8d',
      'r9d',
      'r10d',
      'r11d',
      'r12d',
      'r13d',
      'r14d',
      'r15d',
      'ax',
      'bx',
      'cx',
      'dx',
      'sp',
      'bp',
      'si',
      'di',
      'al',
      'bl',
      'cl',
      'dl',
      'ah',
      'bh',
      'ch',
      'dh',
      'spl',
      'bpl',
      'sil',
      'dil',
      'r8b',
      'r9b',
      'r10b',
      'r11b',
      'r12b',
      'r13b',
      'r14b',
      'r15b',
      'r8w',
      'r9w',
      'r10w',
      'r11w',
      'r12w',
      'r13w',
      'r14w',
      'r15w',
      'rip',
      'rflags',
      'eflags',
      'cs',
      'ds',
      'es',
      'fs',
      'gs',
      'ss',
      'xmm0',
      'xmm1',
      'xmm2',
      'xmm3',
      'xmm4',
      'xmm5',
      'xmm6',
      'xmm7',
      'xmm8',
      'xmm9',
      'xmm10',
      'xmm11',
      'xmm12',
      'xmm13',
      'xmm14',
      'xmm15',
      'ymm0',
      'ymm1',
      'ymm2',
      'ymm3',
      'ymm4',
      'ymm5',
      'ymm6',
      'ymm7',
      'ymm8',
      'ymm9',
      'ymm10',
      'ymm11',
      'ymm12',
      'ymm13',
      'ymm14',
      'ymm15',
    ],

    sizeKeywords: [
      'byte',
      'word',
      'dword',
      'qword',
      'tword',
      'oword',
      'yword',
      'ptr',
    ],

    tokenizer: {
      root: [
        // Comments
        [/;.*$/, 'comment'],
        // Labels (identifier followed by colon at start of line)
        [/^[a-zA-Z_]\w*:/, 'type.identifier'],
        // Hex numbers (0x prefix)
        [/0[xX][0-9a-fA-F]+/, 'number.hex'],
        // Decimal numbers
        [/\b\d+\b/, 'number'],
        // Memory operand brackets
        [/[[\]]/, 'delimiter.bracket'],
        // Identifiers: check against keywords/registers/size-keywords
        [
          /[a-zA-Z_]\w*/,
          {
            cases: {
              '@keywords': 'keyword',
              '@registers': 'variable.predefined',
              '@sizeKeywords': 'keyword.type',
              '@default': 'identifier',
            },
          },
        ],
        // Comma separator
        [/,/, 'delimiter'],
        // Plus/minus in memory operands
        [/[+\-*]/, 'operator'],
      ],
    },
  } as Parameters<typeof monaco.languages.setMonarchTokensProvider>[1]);

  monaco.languages.setLanguageConfiguration('nasm', {
    comments: { lineComment: ';' },
    brackets: [['[', ']']],
    autoClosingPairs: [{ open: '[', close: ']' }],
  });
}

export function defineDebuggerTheme(monaco: Monaco) {
  monaco.editor.defineTheme('debugger-dark', {
    base: 'vs-dark',
    inherit: true,
    rules: [
      { token: 'keyword', foreground: '#569cd6' },
      { token: 'variable.predefined', foreground: '#9cdcfe' },
      { token: 'keyword.type', foreground: '#4ec9b0' },
      { token: 'number', foreground: '#b5cea8' },
      { token: 'number.hex', foreground: '#b5cea8' },
      { token: 'comment', foreground: '#6a9955' },
      { token: 'delimiter.bracket', foreground: '#ffd700' },
      { token: 'type.identifier', foreground: '#dcdcaa' },
      { token: 'operator', foreground: '#d4d4d4' },
      { token: 'delimiter', foreground: '#d4d4d4' },
      { token: 'identifier', foreground: '#dcdcaa' },
    ],
    colors: { 'editor.background': '#1e1e1e' },
  });
}
